version: '3'

services:
  edge-impulse-collector:
    build: .
    command: ./start-collector.sh --h
    network_mode: host
    devices:
      - /dev/video0

  edge-impulse-runner:
    build: .
    command: ./runner.sh -h
    devices:
      - /dev/video0
    ports:
      - 4912:4912
